### ISSUE TITLE
Fix seen counts

### ISSUE THREAD

**Issue by abats** [castor385/episodealert#58]
In the old site we did not remove seen counts after unfollowing a series. It's quite likely man of the seen counts are very wrong because of this.

We can remove unfollowed seen counts with some mega script

**Comment by castor385** [comment]
Can probably be solved by running:

delete seen from seen 
left join following f on f.series_id = seen.series_id 
	and f.user_id = seen.user_id 
where f.id is null;

**Comment by castor385** [comment]
Query executed.
Query OK, 365565 rows affected (4 min 5.31 sec)
